// ========================================
// Job Board Application
// ========================================

// State management
let jobs = [];
let activeFilters = new Set();
let isLoading = false;

// DOM Elements
const jobsContainer = document.getElementById('jobs-container');
const filterBar = document.getElementById('filter-bar');
const filterTagsContainer = document.getElementById('filter-tags-container');
const clearFiltersBtn = document.getElementById('clear-filters');
const refreshBtn = document.getElementById('refresh-btn');
const scrapeLink = document.getElementById('scrape-link');
const jobCountSpan = document.getElementById('job-count');

// ========================================
// Data Fetching Functions
// ========================================

/**
 * Fetch jobs from the JSON file generated by the scraper
 */
async function fetchJobs() {
    if (isLoading) return;
    
    isLoading = true;
    showLoadingState();
    
    try {
        // Add cache-busting timestamp
        const timestamp = new Date().getTime();
        const response = await fetch(`jobs_data.json?t=${timestamp}`);
        
        if (!response.ok) {
            throw new Error(`HTTP ${response.status}: ${response.statusText}`);
        }
        
        const data = await response.json();
        
        // Handle both formats (with wrapper or direct array)
        if (data.jobs && Array.isArray(data.jobs)) {
            jobs = data.jobs;
        } else if (Array.isArray(data)) {
            jobs = data;
        } else {
            jobs = [];
        }
        
        // Update last updated time
        if (data.last_updated) {
            console.log(`Jobs last updated: ${new Date(data.last_updated).toLocaleString()}`);
        }
        
        renderJobs();
        updateJobCount();
        
    } catch (error) {
        console.error('Error fetching jobs:', error);
        showErrorState(`Failed to load jobs: ${error.message}`);
    } finally {
        isLoading = false;
    }
}

/**
 * Trigger a new scrape by calling the Python scraper
 * Note: This requires a backend endpoint in production
 */
async function triggerScrape() {
    showLoadingState();
    
    try {
        // In a production environment, this would call an API endpoint
        // that runs the Python scraper. For demo purposes, we'll simulate.
        
        // Simulate API call
        await new Promise(resolve => setTimeout(resolve, 1500));
        
        // Reload jobs
        await fetchJobs();
        
        // Show success message
        showTemporaryMessage('Jobs refreshed successfully!', 'success');
        
    } catch (error) {
        console.error('Error triggering scrape:', error);
        showTemporaryMessage('Failed to refresh jobs. Please try again.', 'error');
    }
}

// ========================================
// Filtering Functions
// ========================================

/**
 * Add a filter to the active filters set
 */
function addFilter(filter) {
    if (!activeFilters.has(filter)) {
        activeFilters.add(filter);
        updateFilterUI();
        renderJobs();
    }
}

/**
 * Remove a filter from the active filters set
 */
function removeFilter(filter) {
    if (activeFilters.has(filter)) {
        activeFilters.delete(filter);
        updateFilterUI();
        renderJobs();
    }
}

/**
 * Clear all active filters
 */
function clearAllFilters() {
    activeFilters.clear();
    updateFilterUI();
    renderJobs();
}

/**
 * Update the filter UI based on active filters
 */
function updateFilterUI() {
    if (activeFilters.size === 0) {
        filterBar.classList.add('hidden');
        return;
    }
    
    filterBar.classList.remove('hidden');
    filterTagsContainer.innerHTML = '';
    
    activeFilters.forEach(filter => {
        const tag = document.createElement('div');
        tag.className = 'filter-tag';
        tag.innerHTML = `
            <span class="filter-tag-text">${escapeHtml(filter)}</span>
            <button class="filter-tag-remove" data-filter="${escapeHtml(filter)}" aria-label="Remove filter ${escapeHtml(filter)}">
                <i class="fas fa-times" aria-hidden="true"></i>
            </button>
        `;
        filterTagsContainer.appendChild(tag);
    });
    
    // Add event listeners to remove buttons
    document.querySelectorAll('.filter-tag-remove').forEach(btn => {
        btn.addEventListener('click', () => {
            const filter = btn.dataset.filter;
            removeFilter(filter);
        });
    });
}

/**
 * Filter jobs based on active filters
 */
function getFilteredJobs() {
    if (activeFilters.size === 0) return jobs;
    
    return jobs.filter(job => {
        // Create a set of all tags for this job
        const jobTags = new Set();
        
        if (job.role) jobTags.add(job.role);
        if (job.level) jobTags.add(job.level);
        if (job.languages && Array.isArray(job.languages)) {
            job.languages.forEach(lang => jobTags.add(lang));
        }
        if (job.tools && Array.isArray(job.tools)) {
            job.tools.forEach(tool => jobTags.add(tool));
        }
        
        // Check if all active filters are present in job tags
        for (const filter of activeFilters) {
            if (!jobTags.has(filter)) return false;
        }
        
        return true;
    });
}

/**
 * Update the job count display
 */
function updateJobCount() {
    const filteredJobs = getFilteredJobs();
    jobCountSpan.textContent = filteredJobs.length;
}

// ========================================
// Rendering Functions
// ========================================

/**
 * Render jobs to the DOM
 */
function renderJobs() {
    const filteredJobs = getFilteredJobs();
    updateJobCount();
    
    if (filteredJobs.length === 0) {
        showEmptyState();
        return;
    }
    
    // Clear container
    jobsContainer.innerHTML = '';
    
    // Render each job card
    filteredJobs.forEach(job => {
        const jobCard = createJobCard(job);
        jobsContainer.appendChild(jobCard);
    });
}

/**
 * Create a job card DOM element
 */
function createJobCard(job) {
    const card = document.createElement('article');
    card.className = `job-card ${job.is_featured ? 'featured' : ''}`;
    card.setAttribute('aria-label', `Job: ${job.position} at ${job.company}`);
    
    // Get initial for logo fallback
    const initial = job.company ? job.company.charAt(0).toUpperCase() : 'J';
    
    card.innerHTML = `
        <div class="job-logo" aria-hidden="true">
            ${job.logo ? 
                `<img src="images/${job.logo}" alt="${job.company} logo" onerror="this.style.display='none'; this.nextSibling.style.display='flex'">` : 
                ''
            }
            <i class="fas fa-briefcase" style="${job.logo ? 'display: none;' : ''}"></i>
        </div>
        <div class="job-info">
            <div class="job-header">
                <span class="company-name">${escapeHtml(job.company)}</span>
                ${job.is_new ? '<span class="badge badge-new" aria-label="New job posting">New!</span>' : ''}
                ${job.is_featured ? '<span class="badge badge-featured" aria-label="Featured job">Featured</span>' : ''}
            </div>
            <h2 class="job-title">
                <a href="#" aria-describedby="job-details-${job.id}">${escapeHtml(job.position)}</a>
            </h2>
            <div class="job-details" id="job-details-${job.id}">
                <span><i class="far fa-clock" aria-hidden="true"></i> ${escapeHtml(job.posted_at || 'Recently')}</span>
                <span><i class="far fa-calendar-alt" aria-hidden="true"></i> ${escapeHtml(job.contract || 'Full Time')}</span>
                <span><i class="fas fa-map-marker-alt" aria-hidden="true"></i> ${escapeHtml(job.location || 'Remote')}</span>
            </div>
        </div>
        <div class="job-tags">
            ${job.role ? `<button class="tag" data-filter="${escapeHtml(job.role)}">${escapeHtml(job.role)}</button>` : ''}
            ${job.level ? `<button class="tag" data-filter="${escapeHtml(job.level)}">${escapeHtml(job.level)}</button>` : ''}
            ${(job.languages || []).map(lang => `<button class="tag" data-filter="${escapeHtml(lang)}">${escapeHtml(lang)}</button>`).join('')}
            ${(job.tools || []).map(tool => `<button class="tag" data-filter="${escapeHtml(tool)}">${escapeHtml(tool)}</button>`).join('')}
        </div>
    `;
    
    // Add event listeners to filter buttons
    const tags = card.querySelectorAll('.tag');
    tags.forEach(tag => {
        tag.addEventListener('click', (e) => {
            e.preventDefault();
            const filter = tag.dataset.filter;
            addFilter(filter);
        });
    });
    
    return card;
}

/**
 * Show loading state
 */
function showLoadingState() {
    jobsContainer.innerHTML = `
        <div class="loading-state">
            <div class="spinner"></div>
            <p>Loading job listings...</p>
        </div>
    `;
}

/**
 * Show empty state when no jobs match filters
 */
function showEmptyState() {
    jobsContainer.innerHTML = `
        <div class="empty-state">
            <i class="fas fa-search" aria-hidden="true"></i>
            <h3>No jobs found</h3>
            <p>Try removing some filters to see more opportunities.</p>
            <button class="refresh-btn" id="reset-filters-btn" style="margin-top: 1rem;">Reset Filters</button>
        </div>
    `;
    
    const resetBtn = document.getElementById('reset-filters-btn');
    if (resetBtn) {
        resetBtn.addEventListener('click', clearAllFilters);
    }
}

/**
 * Show error state
 */
function showErrorState(message) {
    jobsContainer.innerHTML = `
        <div class="error-state">
            <i class="fas fa-exclamation-triangle" style="font-size: 3rem; margin-bottom: 1rem;" aria-hidden="true"></i>
            <h3>Something went wrong</h3>
            <p>${escapeHtml(message)}</p>
            <button class="refresh-btn" id="retry-btn" style="margin-top: 1rem;">Try Again</button>
        </div>
    `;
    
    const retryBtn = document.getElementById('retry-btn');
    if (retryBtn) {
        retryBtn.addEventListener('click', fetchJobs);
    }
}

/**
 * Show temporary message
 */
function showTemporaryMessage(message, type = 'info') {
    // Create message element
    const msgDiv = document.createElement('div');
    msgDiv.className = `toast-message toast-${type}`;
    msgDiv.textContent = message;
    
    document.body.appendChild(msgDiv);
    
    // Remove after 3 seconds
    setTimeout(() => {
        msgDiv.style.animation = 'slideOut 0.3s ease';
        setTimeout(() => msgDiv.remove(), 300);
    }, 3000);
}

/**
 * Escape HTML to prevent XSS
 */
function escapeHtml(str) {
    if (!str) return '';
    const div = document.createElement('div');
    div.textContent = str;
    return div.innerHTML;
}

// ========================================
// Event Listeners & Initialization
// ========================================

// Event listeners
clearFiltersBtn.addEventListener('click', clearAllFilters);
refreshBtn.addEventListener('click', triggerScrape);

if (scrapeLink) {
    scrapeLink.addEventListener('click', (e) => {
        e.preventDefault();
        triggerScrape();
    });
}

// Keyboard navigation support for filter tags
document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && activeFilters.size > 0) {
        clearAllFilters();
    }
});

// Initialize app
async function init() {
    await fetchJobs();
}

init();